version: '3.8'

services:
  app:
    image: rifatsoftdev/dting-auth
    build: .
    container_name: dting-auth
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"

  