name: DTing_Server CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -q || true

  deploy:
      needs: test
      runs-on: ubuntu-latest

      steps:
        - name: Deploy to EC2
          uses: appleboy/ssh-action@v1.2.0
          with:
            host: ${{ secrets.AWS_HOST }}
            username: ${{ secrets.AWS_USER }}
            key: ${{ secrets.AWS_KEY }}
            script: |
              cd DTing_Server/
              git pull origin main

              if [ ! -f .env ]; then
                echo "✗ .env file not found on server. Aborting deploy."
                exit 1
              fi

              docker stop dting-server || true
              docker rm dting-server || true
              docker build --no-cache -t dting-server .
              docker run -d \
                --name dting-server \
                --env-file .env \
                --restart unless-stopped \
                -p 8000:8000 \
                dting-server